#! /bin/sh

xrandr --output VGA-0 --auto
xrandr --output VGA-0 --rotate left
xrandr --output HDMI-0 --auto
xrandr --output VGA-0 --mode 1920x1080 --output HDMI-0 --mode 1920x1080 --left-of VGA-0


compton -b
feh --bg-scale candy/dv.jpg 
#feh --bg-scale candy/arch.jpg 
conky & conky -c ~/.conky/conkyrc_HUD
gnome-screensaver & terminator -T vim -x xdotool type ' 
  _    _      _                                   
 | |  | |    | |                                  
 | |  | | ___| | ___ ___  _ __ ___   ___          
 | |/\| |/ _ \ |/ __/ _ \| '_ ` _ \ / _ \         
 \  /\  /  __/ | (_| (_) | | | | | |  __/_        
  \/  \/ \___|_|\___\___/|_| |_| |_|\___( )       
                                        |/

                   ___  ___          _ 
                   |  \/  |         | |           
 _ __ ___  _   _   | .  . | __ _ ___| |_ ___ _ __ 
| '_ ` _ \| | | |  | |\/| |/ _` / __| __/ _ \ '__|
| | | | | | |_| |  | |  | | (_| \__ \ ||  __/ |   
|_| |_| |_|\__, |  \_|  |_/\__,_|___/\__\___|_|   
            __/ |                                
           |___/                                 

' & terminator -T Shell & mpg123 ~/candy/startup3_1.mp3



