// Generated by CoffeeScript 1.9.1
(function() {
  var UIComponentServer, registerPort, root;

  registerPort = function(event) {
    return chrome.storage.local.get("vimiumSecret", function(arg) {
      var secret;
      secret = arg.vimiumSecret;
      if (!(event.source === window.parent && event.data === secret)) {
        return;
      }
      UIComponentServer.portOpen(event.ports[0]);
      return window.removeEventListener("message", registerPort);
    });
  };

  window.addEventListener("message", registerPort);

  UIComponentServer = {
    ownerPagePort: null,
    handleMessage: null,
    portOpen: function(ownerPagePort) {
      this.ownerPagePort = ownerPagePort;
      return this.ownerPagePort.onmessage = (function(_this) {
        return function(event) {
          if (_this.handleMessage) {
            return _this.handleMessage(event);
          }
        };
      })(this);
    },
    registerHandler: function(handleMessage) {
      this.handleMessage = handleMessage;
    },
    postMessage: function(message) {
      if (this.ownerPagePort) {
        return this.ownerPagePort.postMessage(message);
      }
    }
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.UIComponentServer = UIComponentServer;

}).call(this);
