#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-08-06 23:24:17 CEST
# Path:   ~/.config/kitty/kitty.conf
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------

# themes
include tokyonight_moon.conf
#include Wryan.conf
#include VSCode_Dark.conf

confirm_os_window_close 0

# terminal opacity and blur
background_opacity 1.0
background_blur 1

# advance
#term xterm-kitty

# terminal bell
enable_audio_bell no

# os specific tweaks (Gnome window decoration for wayland)
linux_display_server x11

# font
font_family        JetBrains Mono Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size 12.0

# font size management
map ctrl+shift+backspace change_font_size all 0

# cursor customization
# block / beam / underline
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

# scrollback
scrollback_lines 5000
wheel_scroll_multiplier 3.0

# mouse
mouse_hide_wait -1

# window layout
remember_window_size  no
initial_window_width 989
initial_window_height 1058
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations no

# window management
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# layout management
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack

# tab bar customization
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal

# tab management
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab

# Copy pasting
map alt+v paste_from_clipboard

# Font size
map ctrl+equal increase_font_size
map ctrl+minus decrease_font_size
map alt+0 reset_font_size
