# vim: set ft=cfg noai nu et ts=2 sw=2:
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-09-07 02:52:26 CEST
# Path:   ~/.local/share/gnupg/gpg-agent.conf
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------
default-cache-ttl 36000
max-cache-ttl 86400
