# vim: set ft=dosini noai nu et ts=2 sw=2:
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-08-11 19:18:24 CEST
# Path:   ~/.config/fuzzel/fuzzel.ini
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------

[colors]
background=1e2030ff
text=c8d3f5ff
match=65bcffff
selection=363c58ff
selection-match=65bcffff
selection-text=c8d3f5ff
border=589ed7ff
