# vim: set ft=desktop noai nu et ts=2 sw=2:
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-08-11 00:57:36 CEST
# Path:   ~/.local/share/icons/default/index.theme
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------
[Icon Theme]
Name=Default
Comment=Default Cursor Theme
Inherits=riddle-cursors
