# vim: set ft=dosini noai nu et ts=2 sw=2:
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-08-11 19:18:42 CEST
# Path:   ~/.config/gtk-4.0/settings.ini
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------

[Settings]
gtk-application-prefer-dark-theme=true
gtk-theme-name=Adwaita-dark
gtk-icon-theme-name=la-capitaine
gtk-font-name=Inter, 11
gtk-cursor-theme-name=riddle-cursors
gtk-cursor-theme-size=24
gtk-decoration-layout=icon:minimize,maximize,close
gtk-enable-animations=true
gtk-modules=colorreload-gtk-module
gtk-primary-button-warps-slider=false
gtk-xft-dpi=98304
