preload = "~/.config/hypr/wallpapers/solid073542.png"
wallpaper = HDMI-A-1,"~/.config/hypr/wallpapers/solid073542.png"
wallpaper = DP-1,"~/.config/hypr/wallpapers/solid073542.png"
wallpaper = DP-2,"~/.config/hypr/wallpapers/solid073542.png"
