# vim: set ft=conf noai nu et ts=2 sw=2:
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-08-11 19:18:48 CEST
# Path:   ~/.config/hypr/hyprpaper.conf
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------

preload = "~/.config/hypr/wallpapers/solid073542.png"
wallpaper = HDMI-A-1,"~/.config/hypr/wallpapers/solid073542.png"
wallpaper = DP-1,"~/.config/hypr/wallpapers/solid073542.png"
wallpaper = DP-2,"~/.config/hypr/wallpapers/solid073542.png"
