#!/usr/bin/env sh
# This file configures external key events. 
# "C-x" first needs to be pressed to send the next key to the external
# key-handler.
while read file
do
    case "$1" in
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        esac
done
