#!/usr/bin/env bash
# vim:ft=bash:tw=79
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2024-07-18 16:25:39 EEST
# Path:   ~/.config/nsxiv/exec/key-handler
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------
#*
# This file configures external key events. 
# 
# "C-x" first needs to be pressed to send the next key to the external
# key-handler.
#**

while read file
do
    case "$1" in
    "r")
        convert -rotate 90 "$file" "$file" ;;
    "R")
        convert -rotate -90 "$file" "$file" ;;
    "d")
        [[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ]] \
        && rm "$file" && notify-send "$file deleted." ;;
        esac
done
