# vim: set ft=toml tw=79 nu ai et ts=2 sw=2:
# -----------------------------------------------------------------------------
# User: 00riddle00 (Tomas Giedraitis)
# Date: 2026-08-11 19:13:31 CEST
# Path: ~/.config/alacritty/tokyonight_moon.toml
# URL:  https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------
# Author: folke (Folke Lemaitre) (https://folke.io)
# Orig. URL: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_moon.toml
# Orig. URL/File Retrieval: 2025-10-25 19:27:04 EEST
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff8d94'
green = '#c7fb6d'
yellow = '#ffd8ab'
blue = '#9ab8ff'
magenta = '#caabff'
cyan = '#b2ebff'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
