#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-08-07 04:45:22 CEST
# Path:   ~/.config/sway/config.d/50-systemd-user.conf
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------
# sway does not set DISPLAY/WAYLAND_DISPLAY in the systemd user environment
# See FS#63021
# Adapted from xorg's 50-systemd-user.sh, which achieves a similar goal.

# Upstream refuses to set XDG_CURRENT_DESKTOP so we have to.
exec systemctl --user set-environment \
    XDG_CURRENT_DESKTOP=sway

exec systemctl --user import-environment \
    DISPLAY \
    SWAYSOCK \
    WAYLAND_DISPLAY \
    XDG_CURRENT_DESKTOP

exec hash dbus-update-activation-environment 2>/dev/null && \
    dbus-update-activation-environment --systemd \
        DISPLAY \
        SWAYSOCK \
        XDG_CURRENT_DESKTOP=sway \
        WAYLAND_DISPLAY

# Add GTK theme environment variables
exec systemctl --user set-environment GTK_THEME=Adwaita-dark
exec systemctl --user set-environment XDG_SESSION_DESKTOP=sway
exec systemctl --user set-environment GDK_BACKEND=wayland,x11
