# vim: set ft=toml tw=79 nu ai et ts=2 sw=2:
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-08-11 19:27:33 CEST
# Path:   ~/.config/ruff/ruff.toml
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------
#*
# Ruff default configuration file. Neovim's Ruff uses this config is no other
# config file (e.g. pyproject.toml) is found in the project directory.
#**
line-length = 88

[lint]
select = ["E", "F", "I"]
fixable = ["ALL"]
