#!/usr/bin/env bash
# vim: set ft=bash tw=79 nu ai et ts=2 sw=2:
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2026-08-10 06:14:21 CEST
# Path:   ~/.config/openbox/autostart
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------
#*
# These user-specific programs are run when an Openbox X Session is started.
# All the other autostart programs are started in ${XDG_CONFIG_HOME}/X11/xinitrc
#**
hsetroot -solid "${COL_BG_SEACOLOR}" &

if [[ "$(hostname)" == "tulkun" ]]; then
  picom -b > "${XDG_RUNTIME_DIR}/picom.log" 2>&1
fi

tint2 > "${XDG_RUNTIME_DIR}/tint2.log" 2>&1 &

# Bridge modern AppIndicator (SNI) tray icons to XEmbed (tint2)
(
  sleep 2
  snixembed > "${XDG_RUNTIME_DIR}/snixembed.log" 2>&1
) &

term-standard &

pgrep -x anydesk >/dev/null || anydesk &
