#!/usr/bin/env bash
# vim:ft=bash:tw=79:sw=2:ts=2:sts=2:et
#------------------------------------------------------------------------------
# Author: 00riddle00 (Tomas Giedraitis)
# Date:   2024-09-28 22:31:26 EEST
# Path:   ~/.config/openbox/autostart
# URL:    https://github.com/00riddle00/dotfiles
#------------------------------------------------------------------------------
#*
# These user-specific things are run when an Openbox X Session is started.
#**

#picom -b > /dev/null 2>&1 &

hsetroot -solid "#073542" &

tint2 > /dev/null 2>&1 &

urxvt -name t2 &
